# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-
#
$:.push File.expand_path('../lib', __FILE__)
version = File.exist?('VERSION') ? File.read('VERSION') : ""

Gem::Specification.new do |s|
  s.name = %q{simplificator-filter}
  s.version = version
  s.platform = Gem::Platform::RUBY
  s.authors = ["Alessandro Di Maria", "Pascal Betz", "Fabio Kuhn"]
  s.email = %q{info@simplificator.com}
  s.homepage = 'http://github.com/simplificator/simplificator-filter'
  s.summary = %q{Filter and order AR objects the Rails3 way}
  s.description = %q{An attempt to generalize filtering/ordering of AR objects from params}
  s.rubyforge_project = 'simplificator-filter'


  s.required_rubygems_version = '>= 1.3.7'

  s.add_dependency 'meta_where', '~> 0.9.6'
  s.add_dependency 'activerecord', "= 3.0.10"
  s.add_development_dependency 'shoulda'
  s.add_development_dependency 'sqlite3-ruby', ">= 1.2.5"
  s.add_development_dependency 'mysql'
  s.add_development_dependency 'pg'

  s.files = Dir.glob('{lib}/**/*') + %w[LICENSE README.textile]
  s.require_path = 'lib'
end